### ISSUE TITLE
plotting results

### ISSUE THREAD

**Issue by johstu** [khliland/pls#29]
II have a really specific question regarding the plotting of my results from PLSR. My PLSR formula is Age ~ 400BrainRegions.
I would like to have an image that shows the importance of brain regions for age prediction, but also includes the direction of effect. For clarification, I included an example image below in which I projected the x loadings of the first LV onto the brain. Plotting the x-scores of LV1 across age, we have a negative correlation (= decreasing scores with increasing age). 

So, my question: does the color of the region already tell the direction of effect? So in my example image this would mean: while primary processing networks decrease across age (red, positive loading), higher order networks increase (blue, negative loading). Or do I somehow additionally need to account for the loading weights to picture both, the importance of regions as well as the direction of effect?

Thanks for your help!
Johanna

<img width="343" alt="Bildschirmfoto 2020-06-26 um 11 44 36" src="https://user-images.githubusercontent.com/56960478/85844375-eef77080-b7a2-11ea-92d1-656c44ac7aaa.png">

**Comment by bhmevik** [comment]
As far as I know, there isn't much theory about whether the loadings or the loading weights are better at showing the direction of an effect in PLSR. PLSR has more a focus on predictions and visible explorations of the relationships than on theoretical connections and statistical tests.
