### ISSUE TITLE
Same results using different methods for pls2

### ISSUE THREAD

**Issue by statslover123** [khliland/pls#35]
Hello,

I get the same results (accuracy of out of sample prediction) with kernelpls, orthogonal pls, and widekernel pls. Is this expected?

**Comment by khliland** [comment]
Hi statslover123,

This is the expected outcome. The different algorithms have different strengths with regard to computational efficiency and different numerical characteristics in some situations, but should essentially give the same results. The default kernel version is generally quick and precise, the simpls is quick, but not necessarily as precise, orthogonal scores is basically the original PLS - precise, but not very quick, and the cppls version enables additional responses, powered loading weights and mixed classification and regression responses.

**Comment by statslover123** [comment]
thank you
